import type { Skill } from '@/types/skill'

export const SKILLS_DATA: Skill[] = [
  {
    id: 'wallet-digest',
    name: 'Wallet Digest',
    version: '1.0.0',
    tier: 'free',
    category: 'monitoring',
    trigger_type: 'scheduled',
    tagline: 'Full on-chain wallet intelligence in one shot',
    description: 'Analyzes a wallet\'s full on-chain activity — token balances, recent transactions, PnL, and behavioral patterns — then generates a structured digest with key observations and risk flags.',
    deps: [],
    compat: ['base', 'ethereum', 'arbitrum'],
    config_schema: [
      { k: 'wallet_address', type: 'text', label: 'Wallet Address', placeholder: '0x...', required: true },
      { k: 'time_window', type: 'select', label: 'Time Window', required: false, default: '24h', options: ['1h', '24h', '7d', '30d'] }
    ],
    author: 'kernal-labs',
    installs: 2847,
    executions: 18423,
    risk_level: 'Low',
    gas_cost: 'None',
    status: 'live',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: 'token-alert',
    name: 'Token Alert',
    version: '1.0.0',
    tier: 'free',
    category: 'monitoring',
    trigger_type: 'on_event',
    tagline: 'Real-time price and volume anomaly detection',
    description: 'Monitors token price movements and volume spikes against configurable thresholds. Alerts when conditions are met with market context and recommended actions.',
    deps: [],
    compat: ['base', 'ethereum'],
    config_schema: [
      { k: 'token', type: 'text', label: 'Token Symbol or Address', placeholder: 'ETH, USDC, or 0x...', required: true },
      { k: 'threshold_pct', type: 'number', label: 'Alert Threshold (%)', placeholder: '5', required: false, default: 5 },
      { k: 'timeframe', type: 'select', label: 'Timeframe', required: false, default: '24h', options: ['1h', '4h', '24h', '7d'] }
    ],
    author: 'kernal-labs',
    installs: 3102,
    executions: 24891,
    risk_level: 'Low',
    gas_cost: 'None',
    status: 'live',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: 'defi-monitor',
    name: 'DeFi Monitor',
    version: '1.0.0',
    tier: 'free',
    category: 'defi',
    trigger_type: 'scheduled',
    tagline: 'LP position health and IL tracking',
    description: 'Monitors DeFi positions across Uniswap v3, Aerodrome, and Curve on Base. Tracks impermanent loss, fee earnings, pool health, and rebalancing signals.',
    deps: [],
    compat: ['base'],
    config_schema: [
      { k: 'position_address', type: 'text', label: 'Pool or Position Address', placeholder: '0x...', required: true },
      { k: 'protocol', type: 'select', label: 'Protocol', required: false, default: 'Uniswap v3', options: ['Uniswap v3', 'Aerodrome', 'Curve', 'Beefy'] }
    ],
    author: 'kernal-labs',
    installs: 1893,
    executions: 11247,
    risk_level: 'Low',
    gas_cost: 'None',
    status: 'live',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: 'yield-optimizer',
    name: 'Yield Optimizer',
    version: '1.0.0',
    tier: 'free',
    category: 'defi',
    trigger_type: 'scheduled',
    tagline: 'Optimal compound timing and yield routing',
    description: 'Analyzes yield farming positions and calculates optimal compound timing based on gas costs, pending rewards, and net APR impact. Routes yield to maximize returns across Base protocols.',
    deps: ['defi-monitor'],
    compat: ['base'],
    config_schema: [
      { k: 'vault_address', type: 'text', label: 'Vault or Pool Address', placeholder: '0x...', required: true },
      { k: 'compound_threshold', type: 'number', label: 'Compound Trigger (% APR gain)', placeholder: '0.5', required: false, default: 0.5 }
    ],
    author: 'kernal-labs',
    installs: 1204,
    executions: 8932,
    risk_level: 'Low',
    gas_cost: 'Low',
    status: 'live',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: 'gas-tracker',
    name: 'Gas Tracker',
    version: '1.0.0',
    tier: 'free',
    category: 'monitoring',
    trigger_type: 'on_event',
    tagline: 'Base gas optimization and timing alerts',
    description: 'Monitors Base network gas prices in real-time and alerts when conditions meet your threshold. Provides timing recommendations for different transaction types based on historical patterns.',
    deps: [],
    compat: ['base'],
    config_schema: [
      { k: 'alert_threshold', type: 'number', label: 'Alert Threshold (gwei)', placeholder: '0.01', required: false, default: 0.01 }
    ],
    author: 'kernal-labs',
    installs: 4231,
    executions: 31847,
    risk_level: 'Low',
    gas_cost: 'None',
    status: 'live',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: 'alpha-digest',
    name: 'Alpha Digest',
    version: '1.0.0',
    tier: 'premium',
    category: 'research',
    trigger_type: 'scheduled',
    tagline: 'Institutional-grade on-chain alpha synthesis',
    description: 'Synthesizes on-chain data, whale wallet movements, and market narrative into a structured alpha report. Identifies conviction trades, rotation signals, and cross-asset opportunities with risk-adjusted scoring.',
    deps: ['wallet-digest', 'token-alert'],
    compat: ['base', 'ethereum', 'arbitrum'],
    config_schema: [
      { k: 'tokens', type: 'text', label: 'Token Watchlist (comma-separated)', placeholder: 'ETH, USDC, AERO', required: true },
      { k: 'whale_wallets', type: 'text', label: 'Whale Wallets to Track (optional)', placeholder: '0x..., 0x...', required: false }
    ],
    author: 'kernal-labs',
    installs: 892,
    executions: 4231,
    risk_level: 'Low',
    gas_cost: 'None',
    status: 'live',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: 'arbitrage-scanner',
    name: 'Arbitrage Scanner',
    version: '1.0.0',
    tier: 'premium',
    category: 'trading',
    trigger_type: 'on_event',
    tagline: 'Cross-DEX arb detection with net profit calc',
    description: 'Scans price discrepancies across Uniswap v3, Aerodrome, and Curve on Base. Calculates net profit after gas and flash loan fees, with execution window estimates and slippage modeling.',
    deps: [],
    compat: ['base'],
    config_schema: [
      { k: 'token_pairs', type: 'text', label: 'Token Pairs (comma-separated)', placeholder: 'ETH/USDC, WBTC/ETH', required: true },
      { k: 'min_profit_usd', type: 'number', label: 'Min Profit Threshold (USD)', placeholder: '50', required: false, default: 50 }
    ],
    author: 'kernal-labs',
    installs: 623,
    executions: 2891,
    risk_level: 'Medium',
    gas_cost: 'Medium',
    status: 'live',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: 'sniper-skill',
    name: 'Sniper',
    version: '1.0.0',
    tier: 'premium',
    category: 'trading',
    trigger_type: 'on_event',
    tagline: 'New pool launch detection and entry execution',
    description: 'Detects new liquidity pool launches on Base and executes entry positions based on configurable filters — minimum liquidity, honeypot check, tax validation. Runs in analysis mode until TGE.',
    deps: [],
    compat: ['base'],
    config_schema: [
      { k: 'max_spend_eth', type: 'number', label: 'Max Spend (ETH)', placeholder: '0.1', required: true },
      { k: 'min_liquidity', type: 'number', label: 'Min Initial Liquidity (ETH)', placeholder: '5', required: false, default: 5 },
      { k: 'honeypot_check', type: 'checkbox', label: 'Enable Honeypot Detection', required: false, default: true }
    ],
    author: 'kernal-labs',
    installs: 1102,
    executions: 5847,
    risk_level: 'High',
    gas_cost: 'Medium',
    status: 'live',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: 'copy-trader',
    name: 'Copy Trader',
    version: '1.0.0',
    tier: 'premium',
    category: 'trading',
    trigger_type: 'on_event',
    tagline: 'Smart money mirroring with configurable delay',
    description: 'Mirrors trades from a specified smart money wallet with configurable delay and position sizing. Includes trade filtering, risk limits, and exit coordination based on wallet behavioral patterns.',
    deps: ['wallet-digest'],
    compat: ['base', 'ethereum'],
    config_schema: [
      { k: 'watch_wallet', type: 'text', label: 'Mirror Wallet Address', placeholder: '0x...', required: true },
      { k: 'max_spend_eth', type: 'number', label: 'Max Spend per Trade (ETH)', placeholder: '0.1', required: true },
      { k: 'delay_minutes', type: 'number', label: 'Entry Delay (minutes)', placeholder: '0', required: false, default: 0 }
    ],
    author: 'kernal-labs',
    installs: 741,
    executions: 3102,
    risk_level: 'High',
    gas_cost: 'Low',
    status: 'live',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: 'mev-guard',
    name: 'MEV Guard',
    version: '1.0.0',
    tier: 'premium',
    category: 'protection',
    trigger_type: 'manual',
    tagline: 'Sandwich attack protection via private mempool routing',
    description: 'Routes transactions through Flashbots Protect or MEV Blocker to prevent sandwich attacks. Analyzes transaction risk level and selects optimal protection mode automatically.',
    deps: [],
    compat: ['base', 'ethereum'],
    config_schema: [
      { k: 'mode', type: 'select', label: 'Protection Mode', required: false, default: 'flashbots', options: ['flashbots', 'mev-blocker', 'auto'] }
    ],
    author: 'kernal-labs',
    installs: 567,
    executions: 2341,
    risk_level: 'Low',
    gas_cost: 'Low',
    status: 'live',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: 'portfolio-rebalancer',
    name: 'Portfolio Rebalancer',
    version: '1.0.0',
    tier: 'premium',
    category: 'automation',
    trigger_type: 'scheduled',
    tagline: 'Drift-based automatic portfolio rebalancing',
    description: 'Monitors portfolio allocation against target weights and triggers rebalancing when drift exceeds threshold. Gas-aware execution with slippage optimization on Base.',
    deps: ['gas-tracker'],
    compat: ['base'],
    config_schema: [
      { k: 'target_eth_pct', type: 'number', label: 'Target ETH Allocation (%)', placeholder: '50', required: false, default: 50 },
      { k: 'drift_threshold', type: 'number', label: 'Rebalance Trigger Drift (%)', placeholder: '5', required: false, default: 5 }
    ],
    author: 'kernal-labs',
    installs: 412,
    executions: 1893,
    risk_level: 'Medium',
    gas_cost: 'Medium',
    status: 'live',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: 'governance-voter',
    name: 'Governance Voter',
    version: '1.0.0',
    tier: 'premium',
    category: 'governance',
    trigger_type: 'on_event',
    tagline: 'Automated DAO voting with rule-based logic',
    description: 'Monitors DAO proposal queues and votes automatically based on configurable rules — keyword matching, proposal type, and quorum thresholds. Supports Snapshot and on-chain governance.',
    deps: [],
    compat: ['base', 'ethereum'],
    config_schema: [
      { k: 'dao_contract', type: 'text', label: 'DAO Contract Address', placeholder: '0x...', required: true },
      { k: 'vote_rule', type: 'text', label: 'Vote YES on Keywords', placeholder: 'security, upgrade, treasury', required: false, default: 'security, upgrade, treasury' }
    ],
    author: 'kernal-labs',
    installs: 289,
    executions: 1204,
    risk_level: 'Low',
    gas_cost: 'Low',
    status: 'live',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  }
]
